# Generated by Django 5.0.3 on 2024-05-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='activate_date',
            new_name='active_date',
        ),
    ]
