# Generated by Django 5.0.5 on 2024-05-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
